Social_Main/Accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login,logout,password_reset,password_reset_done,password_reset_confirm,password_reset_complete
app_name = "Accounts"
urlpatterns=[
    url(r'^login/$',login,{'template_name':'accounts/login.html'},name = 'login'),
    url(r'^logout/$',logout,{'template_name':'accounts/logout.html'},name = 'logout'),
    url(r'^register/$', views.register,name ='register'),
    url(r'^profile/$',views.view_profile,name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$',views.view_profile,name='view_profile_with_pk'),
    url(r'^profile/edit/$',views.edit_profile,name='edit_profile'),
    
    url(r'^change-password/$',views.change_password,name = 'change_password'),
    
    url(r'^reset-password/$',password_reset,{'template_name':
    'accounts/reset_password.html','post_reset_redirect':
    'accounts:password_reset_done','email_template_name':'accounts/reset_password_email.html'},
    name='reset_password'),
    
    url(r'^reset-password/done/$',password_reset_done,{'template_name':
    'accounts/reset_password_done.html'},name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm,{'template_name':'accounts/reset_password_confirm.html',
    'post_reset_redirect':'accounts:password_reset_complete'},name='password_reset_confirm'),

    url(r'^reset-password/complete/$',password_reset_complete,{'template_name':
    'accounts/reset_password_complete.html'},name='password_reset_complete')

]

Social_Main/Social/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from Social import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('Accounts.urls',namespace='accounts')),
    url(r'^home/',include('home.urls',namespace='home')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Social_Main/home/urls.py
from django.conf.urls import url
from home.views import HomeView
from . import views
app_name="home"
urlpatterns=[
    url(r'^$',HomeView.as_view(),name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',
    views.change_friends,name='change_friends')
]

Social_Main/home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Friend(models.Model):
    users = models.ManyToManyField(User )
    current_user = models.ForeignKey(User,related_name='owner',null=True,on_delete=models.CASCADE)

    @classmethod
    def make_friend(cls,current_user,new_friend):
        friend,created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls,current_user,new_friend):
        friend,created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(new_friend)

Social_Main/home/forms.py
from django import forms
from home.models import Post
class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs = {
            'class': 'form-control',
            'placeholder':'Write a post...' 
        }
    ))

    class Meta:
        model = Post
        fields = ('post',)

Social_Main/home/views.py
from django.views.generic import TemplateView
from home.forms import HomeForm
from home.models import Post,Friend
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
class HomeView(TemplateView):
    template_name='home/home.html'

    def get(self,request):
        form = HomeForm()
        posts = Post.objects.all().order_by('-created')
        users = User.objects.exclude(id=request.user.id)
        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()

        args = {
            'form': form,'posts': posts,'users':users,'friends':friends
        }
        return render(request,self.template_name,args)

    def post(self,request):
        form  = HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            text = form.cleaned_data['post']
            form = HomeForm()
            return redirect('home:home')

        args={'form': form,'text': text}
        return render(request,self.template_name,args)

def change_friends(request,operation,pk):
    new_friend = User.objects.get(pk=pk)
    if operation=='add':
        Friend.make_friend(request.user,new_friend)
    elif operation=='remove':
        Friend.lose_friend(request.user,new_friend)

    return redirect('home:home')

Social_Main/home/templates/home/home.html
{% extends 'base.html' %}

{% block head %}
<title>Home</title>
<style>
    #wrap {
        background-color: aliceblue
    }

    #okay {
        background-color: aliceblue
    }

    #okay_1 {
        background-color: aliceblue
    }

    #ab {
        background-color: royalblue
    }
    .container_format{
        margin-bottom: 40px;
        border-radius: 50%;
    }
</style>
{% endblock %}

{% block body %}

<body id="ab">

    <div  class="container container_format">
        <br>
        <div class="row">
            <div style="padding-bottom: 20px;" class="col-md-8" id="okay">
                <br>
                <h2 style="padding: 5px;">Home <span class="badge badge-info"> {{ user.get_full_name }}</span></h2>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.post }}
                    <br>
                    <button type="submit" class="btn btn-outline-info">Submit</button>
                </form>
                <h2>{{ text }}</h2>
                {% for post in posts %}
                <div id="wrap">

                    <div style="border-radius: 2%;" class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ post.post }}</h5>
                            <p class="card-text">Posted by {{ post.user.get_full_name }} on {{ post.created }}</p>
                            <a href="#" class="btn btn-primary">Like</a>
                            <a href="#" class="btn btn-success">Comment</a>
                            <a href="#" class="btn btn-secondary">Share</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-md-4" id="okay_1">
                <br>
                <h3>People you may know</h3>
                {% for user in users %}
                {% if not user in friends%}

                <div style="margin: 5px;" class="card flex-row flex-wrap">
                    <div class="card-header border-0">
                        <img class="card-img-top"
                            src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS72bMX-sucG9MRPc5EBVDO0Wh4LtJNtprbRrU-wOxGZOgNOFsi"
                            alt={{ user.get_full_name }} style="width: 70px;height: 70px;">
                    </div>
                    <div class="card-block px-2">
                        <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
                            <h5 style="padding: 5px;" class="card-title">{{ user.get_full_name }}</h5>
                        </a>
                        <a href="{% url 'home:change_friends' operation='add' pk=user.pk %}">
                            <button type="button" class="btn btn-outline-success">Add Friend</button>
                        </a>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
                <hr>
                    <h3>Your Friends</h3>
                    {% for friend in friends %}
                    <div style="margin: 5px;" class="card flex-row flex-wrap">
                        <div class="card-header border-0">
                            <img class="card-img-top"
                                src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS72bMX-sucG9MRPc5EBVDO0Wh4LtJNtprbRrU-wOxGZOgNOFsi"
                                alt={{ user.get_full_name }} style="width: 70px;height: 70px;">
                        </div>
                        <div class="card-block px-2">
                            <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
                                <h5 style="padding: 5px;" class="card-title">{{ friend.get_full_name }}</h5>
                            </a>
                            <a href="{% url 'home:change_friends' operation='remove' pk=friend.pk %}">
                                <button type="button" class="btn btn-outline-danger">Remove Friend</button>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
            </div>
        </div>
    </div>
</body>
{% endblock %}