Social_Main/Accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login,logout,password_reset,password_reset_done,password_reset_confirm,password_reset_complete
app_name = "Accounts"
urlpatterns=[
    url(r'^login/$',login,{'template_name':'accounts/login.html'},name = 'login'),
    url(r'^logout/$',logout,{'template_name':'accounts/logout.html'},name = 'logout'),
    url(r'^register/$', views.register,name ='register'),
    url(r'^profile/$',views.view_profile,name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$',views.view_profile,name='view_profile_with_pk'),
    url(r'^profile/edit/$',views.edit_profile,name='edit_profile'),
    
    url(r'^change-password/$',views.change_password,name = 'change_password'),
    
    url(r'^reset-password/$',password_reset,{'template_name':
    'accounts/reset_password.html','post_reset_redirect':
    'accounts:password_reset_done','email_template_name':'accounts/reset_password_email.html'},
    name='reset_password'),
    
    url(r'^reset-password/done/$',password_reset_done,{'template_name':
    'accounts/reset_password_done.html'},name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm,{'template_name':'accounts/reset_password_confirm.html',
    'post_reset_redirect':'accounts:password_reset_complete'},name='password_reset_confirm'),

    url(r'^reset-password/complete/$',password_reset_complete,{'template_name':
    'accounts/reset_password_complete.html'},name='password_reset_complete')

]

Social_Main/Social/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from Social import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('Accounts.urls',namespace='accounts')),
    url(r'^home/',include('home.urls',namespace='home')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Social_Main/home/urls.py
from django.conf.urls import url
from home.views import HomeView
from . import views
app_name="home"
urlpatterns=[
    url(r'^$',HomeView.as_view(),name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',
    views.change_friends,name='change_friends')
]

Social_Main/Accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager,self).get_queryset().filter(city='Los Angeles')

class UserProfile(models.Model):
    user = models.OneToOneField(User,models.CASCADE)
    description = models.CharField(max_length=100,default='')
    city = models.CharField(max_length=100,default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image',blank=True)

    los_angeles = UserProfileManager()
    def __str__(self):
        return self.user.username

def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile,sender=User)

Social_Main/Accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = {
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        }
        def save(self,commit=True):
            user = super(self,RegistrationForm).save(commit=False)
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            user.email = self.cleaned_data['email']

            if commit:
                user.save()

            return user

class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = {
            'first_name',
            'last_name',
            'email',
            'password'
        }

Social_Main/Accounts/views.py
from django.shortcuts import render,redirect
from Accounts.forms import RegistrationForm , EditProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:home'))
    else:
        form = RegistrationForm()
        args = {'form':form}
        return render(request,'accounts/reg_form.html',args)

def view_profile(request,pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user':user}
    return render(request,'accounts/profile.html',args)

def edit_profile(request):
    if request.method =='POST':
        form = EditProfileForm(request.POST,instance = request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance = request.user)
        args = {'form':form}
        return render(request,'accounts/edit_profile.html',args)

def change_password(request):
    if request.method =='POST':
        form = PasswordChangeForm(data = request.POST,user = request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))

    else:
        form = PasswordChangeForm(user = request.user)
        args = {'form':form}
        return render(request,'accounts/change_password.html',args)

Social_Main/Accounts/templates/base.html
<html lang="en">
<head>

    <link rel="stylesheet" 
href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
crossorigin="anonymous">

<link rel="stylesheet" href="style.css">

<meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block head %}
    <title>The Social Network</title>
    <style>
        body{
             background-color:cornflowerblue;
             /* background-image: url(C:\Users\Shivam\PycharmProjects\Social\Accounts\templates\ABCD.jpg); */
        }
    </style>
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
            <a class="navbar-brand" href="/accounts/login">The Social Network</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarsExample09">
                {% if user.is_authenticated %}
              <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'accounts:view_profile' %}">Profile <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                            <a class="nav-link" href="{% url 'accounts:edit_profile' %}">Edit Profile <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                            <a class="nav-link" href="{% url 'accounts:change_password' %}">Change Password <span class="sr-only">(current)</span></a>
                    </li>
              </ul>
              <ul class="navbar-nav navbar-right">
                    <li class="nav-item active">
                            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout <span class="sr-only">(current)</span></a>
                        </li>    
              </ul>
    {% else %}

    <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:reset_password' %}">Reset Password <span class="sr-only">(current)</span></a>
            </li>
      </ul>

    <form class="form-inline my-2 my-lg-0">
            <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'accounts:login' %}" style="color:black">Login <span class="sr-only">(current)</span></a>
                    </li>
              </ul>
    
        <a class="btn btn-primary" href="{% url 'accounts:register' %}" role="button">Register</a>
    </form>
    {% endif %}


            </div>
          </nav>
    {% block body %}
    <h1>Base</h1>
    {% endblock %}
</body>

<script
  src="http://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</html>